server {
    listen 9999;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # 支持 React Router / 单页路由回退，确保页面刷新不出现 404
        try_files $uri $uri/ /index.html;
    }
}
